travis:
  secure:
    BINSTAR_TOKEN: ioZ+SA2NDBcsKa1Ujis4s9wI5bqpJw+xp8OTdIB9uy2Hxd0bAL0CcJOeZX2DR2ynXLqsDI2doIYcm5XqXjpTLOaOOF9HPtWIACGOadRGC4o4YT9ggIhnGIjUCBKlXzaQG91MCmhTlBKTlZfuOKx2UzKPPl6wRBYp2+8U6wQp7CZllosOwBk6EA+cJMijUVNihMfFtO9HndgdN30AUHeKV2mbUHgQ2vkWpU2PiPZwLZK+6TqA6m9YUnQtGgUFfo2FXU2V3gTGRDkB1Gsg6EJ6BB5VLbKBv18W6am7QJ1kRZyuaeUP3Ozj/Fe8PqMPj9cxqF0HnpnZPkljIwsYhwm+lwc7+WeQOR57Rt36B4adMlgjWXW6cXsNKVgUAV6o0YhWE3X0XJUIQprMNg0HcnCi7tTaEY1pVYSQfDoR1FWk8NUBVGGloHNkhvzcETZIlFRO8wm1w++dBYSwFSBTbJ6eghpOI0yZpoBICRxRkLW4NVHTGycEKXGWKCbijRYy6d5R25Kuoi6bZTOygOW9mspjiaIkTWE+TuE1xRqmDovnpqiejxM5kVXMvXqHqoTw3oOeEBGEk2J8pcZIiM+4zjV8gu8zFkF0hAgAxkAFqwH6TE0EM0OhPCngKmIKlo+k3TW5H9xvs9UkucN1dMPrw3Wr+0jLpKv27V9+8svgezvHODU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
